name: 📑 Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.13
        auto-update-conda: true

    - name: Initialize Conda
      shell: bash -l {0}
      run: conda init bash

    - name: Create Conda Environment
      shell: bash -l {0}
      run: |
        conda env remove -n sphinx_rtd || true
        conda env create --file docs/sphinx_env.yml

    - name: Activate Conda Environment and Check Packages
      shell: bash -l {0}
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate sphinx_rtd
        conda list
        which sphinx-build
        sphinx-build --version

    - name: Generate API Documentation
      shell: bash -l {0}
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate sphinx_rtd
        sphinx-apidoc -o docs/source/api arcjetCV

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate sphinx_rtd
        pip install -e .

    - name: Build Documentation
      shell: bash -l {0}
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate sphinx_rtd
        cd docs
        sphinx-build -b html docs/source docs/build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html