name: Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        auto-update-conda: true

    - name: Create and Activate Conda Environment
      run: |
        conda env create --file docs/sphinx_env.yml
        echo "conda activate sphinx-env" >> $GITHUB_ENV

    - name: Install dependencies
      run: pip install -e .

    - name: Build Documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html