name: CI for arcjetCV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Conda
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc
        conda create -n arcjetCV python=3.13 -y
        echo "conda activate arcjetCV" >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate arcjetCV
        conda install -c conda-forge pip
        pip install -r requirements.txt

    - name: Install arcjetCV
      shell: bash -l {0}
      run: |
        conda activate arcjetCV
        pip install -e .

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate arcjetCV
        pytest

    - name: Deactivate environment
      if: always()
      shell: bash -l {0}
      run: |
        conda deactivate || true
